export const images = {
  none_position: { src: '/img/position/none.svg', alt: 'none position' },
  top: { src: '/img/position/top.svg', alt: 'top lane' },
  jungle: { src: '/img/position/jungle.svg', alt: 'jungle lane' },
  mid: { src: '/img/position/mid.svg', alt: 'mid lane' },
  bottom: { src: '/img/position/bottom.svg', alt: 'bottom lane' },
  support: { src: '/img/position/support.svg', alt: 'support lane' },
  un_rank: { src: '/img/rank/un-rank.png', alt: 'un rank' },
  iron: { src: '/img/rank/icon.png', alt: 'iron rank' },
  bronze: { src: '/img/rank/bronze.png', alt: 'bronze rank' },
  silver: { src: '/img/rank/silver.png', alt: 'silver rank' },
  gold: { src: '/img/rank/gold.png', alt: 'gold rank' },
  platinum: { src: '/img/rank/platinum.png', alt: 'platinum rank' },
  emerald: { src: '/img/rank/emerald.png', alt: 'emerald rank' },
  diamond: { src: '/img/rank/diamond.png', alt: 'diamond rank' },
  master: { src: '/img/rank/master.png', alt: 'master rank' },
  grand_master: { src: '/img/rank/grand-master.png', alt: 'grand master rank' },
  challenger: { src: '/img/rank/challenger.png', alt: 'challenger rank' },
}
